name: 'Commit to README'
description: 'Automagically commit to the readme file'
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run commit.sh
      run: commit.sh
      shell: bash
