on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: zEddSH/recruiter-ready@v1.7
        with:
          who-to-greet: 'Mona the Octocat'
